version: '2'
services:
  mariadb:
    image: 'burgur/mariadb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_PASSWORD=magento_db_password
      - MARIADB_DATABASE=bitnami_magento
  magento:
    image: 'burgur/magento'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_PASSWORD=magento_db_password
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
      - elasticsearch
  phpform:
    image: 'burgur/phpform'
    environment:
      - RestAPIUSER=user
      - RestAPIPASS=bitnami1
      - RestAPIHOST=http://burgur_magento_1
    ports:
      - '8080:80'
    volumes:
      - './code:/var/www/html'
    depends_on:
      - mariadb
      - elasticsearch
      - magento
  elasticsearch:
    image: 'burgur/elastic'
